"""init

Revision ID: 142bb092fb15
Revises: 
Create Date: 2025-04-26 14:25:34.330283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '142bb092fb15'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_url', sa.String(length=255), nullable=False),
    sa.Column('secret_key', sa.String(length=255), nullable=True),
    sa.Column('event_types', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_subscription_id', 'subscriptions', ['id'], unique=False)
    op.create_table('webhook_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('delivery_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('target_url', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_webhook_log_created_at', 'webhook_logs', ['created_at'], unique=False)
    op.create_index('idx_webhook_log_delivery_id', 'webhook_logs', ['delivery_id'], unique=False)
    op.create_index('idx_webhook_log_subscription_id', 'webhook_logs', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_webhook_logs_delivery_id'), 'webhook_logs', ['delivery_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_logs_delivery_id'), table_name='webhook_logs')
    op.drop_index('idx_webhook_log_subscription_id', table_name='webhook_logs')
    op.drop_index('idx_webhook_log_delivery_id', table_name='webhook_logs')
    op.drop_index('idx_webhook_log_created_at', table_name='webhook_logs')
    op.drop_table('webhook_logs')
    op.drop_index('idx_subscription_id', table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
